### ISSUE TITLE
Create test cases for library functions

### ISSUE THREAD

**Issue by karl-cardenas-coding** [karl-cardenas-coding/disaster-cli#10]

**Comment by DanielCardenas-Work** [comment]
Testing the CLI commands here is difficult, because your commands all directly print to Stdout. In principle you could capture what's sent to Stdout and mock calling the commands, but this is hacky unless you decide to literally call a compiled binary.

Since you're using Cobra for commands, I think the best approach for writing tests in Go would be to decouple the Cobra code from the code that provides the data you want to show the user. In other words, your commands should only be calling a function for data, and then printing that data.

This has the following benefits:
1. Code that generates data doesn't have to care if the data will eventually go to the terminal or anywhere else. All data will go through Cobra, which means you can grab it from Cobra during testing as well.
2. Writing new commands will be straightforward, since most functionality would go into helper functions
3. You can later perform in depth tests without having to go through Cobra

[Here's an example of how to grab data from Cobra during testing](https://gianarb.it/blog/golang-mockmania-cli-command-with-cobra)
Essentially, when you write command code you should check if you've been provided a buffer to write to before deciding to write to Stdout. Mocking calling a CLI also isn't very difficult through Cobra as well.

**Comment by karl-cardenas-coding** [comment]
@DanielCardenas-Work Thanks Dani. I created a test case for each call in the `library` folder.  That way I can test each API call and the unique structs. 

I might be leaning towards an external script to invoke the commands. Arduino CLI uses Python. I could do the same or simply author a `bash` script.
